# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

K_tri <- function(x0, x, h, h_pow_d, d) {
    .Call(`_parTreat_K_tri`, x0, x, h, h_pow_d, d)
}

